name: 'Cleanup Test Environment'
description: 'Kill any remaining test processes (safety net for test runner failures)'

runs:
  using: 'composite'
  steps:
    - name: Kill remaining processes
      shell: bash
      if: always()
      run: |
        echo "🧹 Safety cleanup of any remaining processes..."
        pkill -f "trezoa-test-validator" 2>/dev/null || true
        pkill -f "trezoakora" 2>/dev/null || true
        sleep 1
        echo "✅ Cleanup completed"